# Generated by Django 5.2.16 on 2026-07-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='temporal@barbertime.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
